### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/src/png/c++.png'

### ISSUE THREAD

**Issue by rajibdpi** [jayanta525/github-pages-directory-listing#5]
When cpp files are included in repo it seems an error [FileNotFoundError: [Errno 2] No such file or directory: '/src/png/c++.png']. I think it will be work fine if rename the  '/src/png/c++-1.png' to '/src/png/c++.png'.
please check this pull request https://github.com/jayanta525/github-pages-directory-listing/pulls.

Thank you.

**Comment by Zeyu-Xie** [comment]
Same problem today. 🙏
